title: Windows Security Audit
description: Download and operational guide for the enhanced read-only Windows and Active Directory auditor
lang: en-US
theme: jekyll-theme-cayman
show_downloads: false

exclude:

plugins:
  - jekyll-seo-tag
